### PR TITLE
Hotfix/icons

### PR DESCRIPTION
**Pull request by gloriateodoro**
## Contexto
Esse PR faz ajustes que modificam o comportamento dos ícones SVG das páginas technologies, materials e incubations.
Esse PR também refatora o componente ImageText utilizado na página Incubations

## Checklist
- [x]  Technologies/Materials/Incubations: modifica o componente ImageTextListBox para melhorar o comportamento dos ícones na versão mobile.
- [x]  Criação de um arquivo para isolar o componente ImageText, melhorando a visão do código.
- [x]  Substituição do nome ImageText, que estava idêntico a outro componente, para ImageTextIncubations.

### CODE REVIEW

**Comment by bnd-operator** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **lpirola**
You can assign the PR to them by writing `/assign @lpirola` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=nossas%2Fnossas-org).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/nossas/nossas-org/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by bnd-operator** [comment]
@gloriateodoro: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 68b0a0a83cc08b16a2bc41f691bc4729c9f38977 | [link](http://dashboard-jx.35.170.28.138.nip.io/namespaces/jx/pipelineruns/pr-zcc76) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by lpirola** [comment]
@gloriateodoro o build falou, consegue corrigir ante de eu revisar?

**Comment by lpirola** [comment]
```
 > Build error occurred
Error: Build optimization failed: found page without a React Component as default export in 
pages/incubations/ImageTextIncubations

See https://err.sh/vercel/next.js/page-without-valid-component for more info.

	at /usr/src/app/node_modules/next/dist/build/index.js:21:115
	at async /usr/src/app/node_modules/next/dist/build/tracer.js:1:525
error Command failed with exit code 1. 
```

**Comment by gloriateodoro** [comment]
> @gloriateodoro o build falou, consegue corrigir ante de eu revisar?



> @gloriateodoro o build falou, consegue corrigir ante de eu revisar?

Tô vendo isso agora

**Comment by bnd-operator** [comment]
:star: PR built and available in a preview **nossas-nossas-org-pr-32** [here](https://nossas-org-pr32.nossas.org)

**Comment by gloriateodoro** [comment]
> > @gloriateodoro o build falou, consegue corrigir ante de eu revisar?
> 
> > @gloriateodoro o build falou, consegue corrigir ante de eu revisar?
> 
> @lpirola Tô vendo isso agora

@lpirola agora foi?

**Comment by bnd-operator** [comment]
:star: PR built and available in a preview **nossas-nossas-org-pr-32** [here](http://nossas-org-pr32.35.170.28.138.nip.io)

**Comment by bnd-operator** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[lpirola](https://github.com/nossas/nossas-org/pull/32#issuecomment-857113587 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=nossas%2Fnossas-org).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/nossas/nossas-org/blob/main/OWNERS)~~ [lpirola]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
